controller_manager:
  ros__parameters:
    update_rate: 1000 #HZ

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_inside
      - inside_arm
      - rl_l1
      - rl_r1
    interface_name: position 
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity    